// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA5Vk9CWl9PXtTxVXIFpDkA5HXiDDMPCc',
    appId: '1:813218655539:web:3b0c1f85b4d21df0a5a246',
    messagingSenderId: '813218655539',
    projectId: 't2024cs3-campusdiningapp-ac2a3',
    authDomain: 't2024cs3-campusdiningapp-ac2a3.firebaseapp.com',
    storageBucket: 't2024cs3-campusdiningapp-ac2a3.firebasestorage.app',
    measurementId: 'G-X7TKLM5KHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCebRPdq5OKFYhpOT1gVjim953q7bGwbv0',
    appId: '1:813218655539:android:c962efa2f8360b3da5a246',
    messagingSenderId: '813218655539',
    projectId: 't2024cs3-campusdiningapp-ac2a3',
    storageBucket: 't2024cs3-campusdiningapp-ac2a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCguvsTj9DDS8W2iLYor7LdK0ajWVRA4q8',
    appId: '1:813218655539:ios:7bcd17c085303ba2a5a246',
    messagingSenderId: '813218655539',
    projectId: 't2024cs3-campusdiningapp-ac2a3',
    storageBucket: 't2024cs3-campusdiningapp-ac2a3.firebasestorage.app',
    androidClientId: '813218655539-26l70gh5iv3ebe5v1qf0890rdg6c40gq.apps.googleusercontent.com',
    iosClientId: '813218655539-42l8uvtpugj5p9iaci3a6elhl16td4ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.examFetch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCguvsTj9DDS8W2iLYor7LdK0ajWVRA4q8',
    appId: '1:813218655539:ios:7bcd17c085303ba2a5a246',
    messagingSenderId: '813218655539',
    projectId: 't2024cs3-campusdiningapp-ac2a3',
    storageBucket: 't2024cs3-campusdiningapp-ac2a3.firebasestorage.app',
    androidClientId: '813218655539-26l70gh5iv3ebe5v1qf0890rdg6c40gq.apps.googleusercontent.com',
    iosClientId: '813218655539-42l8uvtpugj5p9iaci3a6elhl16td4ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.examFetch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA5Vk9CWl9PXtTxVXIFpDkA5HXiDDMPCc',
    appId: '1:813218655539:web:00523fecde714ce0a5a246',
    messagingSenderId: '813218655539',
    projectId: 't2024cs3-campusdiningapp-ac2a3',
    authDomain: 't2024cs3-campusdiningapp-ac2a3.firebaseapp.com',
    storageBucket: 't2024cs3-campusdiningapp-ac2a3.firebasestorage.app',
    measurementId: 'G-PWFL5MQ36K',
  );

}